appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UvwEvAvOuCcrOIeSoQozYnnvWsoMeFgeOUSITaD2DaBRgztP0XvfB5eKGHOWl5qxHAoWl2ULaE1+VNNbtR0YUHONkW4GMG3d+g7RQV0+Igx6yJiXsld6O7iwKODtEeV6HNtyBN8FqwJ70HM3pdsdcXf3A0cNyQEep783KAzukhX0hWDWbR1KGfG8cEDguO97vPIOQOopQJyMROptIr5u7+Ig1ONIejSlknNvxLTJpwG2EQCTl/9cdul4KpLMS0lhMCtYhbezm+am2WGE+tQW+7CsT/VKhYPPMlrx2ZnDRcvmDeojINM6B7bBcju11TxdyisR2pgTP/rm4HFRr2TnjvYRzloOadUdN2DF0iiJr1ye2ggh+0zh+f1+Dxh6EA4OsK5o8LQn97vsn0UtVzm3F6piido9WsTRCLZ+15JsN6N1WsMQHc8ZTyknfCAXXdAWN02PYMKKcHoHosHt6cb4sYUTAmwpF3NSudGUq7t7oo155fDrjXM7OBkHiA9X3C8NUKDmBTRuTEwpHCJIYtgu+hRDMD2swm5Si498S5dZnb3Kb9eujd3xpMHcDmzAqDoGpWdXivx2GjV7WZtuACz5xOIpyP6QN81LHd52cUSrRJKsmYMHz5ShyEHlBmwsJv2xXXwQj8ZIvoCQEOyVEM/j9L9Q0hdwp5wKOydeTssODl0=}
provider:
  win: azure
bot:
  automerge: true
